server {
    listen 80;
    listen [::]:80;
    server_name _;

    location / {
        root /home/pi/projects/clip-on-vision-assist-satellite/frontend/dist;
    }

    location /api {
        proxy_pass http://control-center-cova.local:42068;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    allow 192.168.4.0/24;
    deny all;
}
