[project]
name = "pi-server"
version = "0.0.1"
requires-python = "==3.9.*"
dependencies = [
    "pydub==0.25.1",
    "pyaudio==0.2.14",
    "httpx==0.28.1",
    "flask==3.1.1",
    "flask-cors==6.0.1",
    "v4l2py==3.0.0",
    "Flask-Pydantic==0.13.1",
    "pydantic==2.11.7",
    "bleak==1.0.1",
    "python-dotenv==1.1.1",
    "pywifi==1.1.12",
    "gunicorn==23.0.0"
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]
